# Generated by Django 5.2.8 on 2025-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
